=== 3dprintpt/RatOS-configuration/boards/board-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://os.ratrig.com/board-definition.schema.json",
	"title": "Control Board",
	"description": "A 3d printer control board",
	"type": "object",
	"properties": {
		"serialPath": {
			"description": "The path for serial communication with this MCU",
			"type": "string"
		},
		"name": {
			"description": "The name of the control board",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this board",
			"type": "string"
		},
		"firmwareBinaryName": {
			"description": "The firmware binary filename in RatOS",
			"type": "string"
		},
		"compileScript": {
			"description": "The path to the compilation script if the board supports automatic firmware compilation, relative to the board definition directory",
			"type": "string"
		},
		"flashScript": {
			"description": "The path to the flashing script if the board supports automatic firmware flashing, relative to the board definition directory",
			"type": "string"
		},
		"flashInstructions": {
			"description": "Instructions for how to make sure the board can be automatically flashed",
			"type": "string"
		},
		"documentationLink": {
			"description": "Link to the RatOS configuration for this board",
			"type": "string"
		},
		"isToolboard": {
			"description": "Whether this controlboard is a toolboard",
			"type": "boolean"
		},
		"isHost": {
			"description": "Whether this is the host computer RatOS is running on (used for Pi)",
			"type": "boolean"
		},
		"disableAutoFlash": {
			"description": "Whether to disable automatic flashing of this board",
			"type": "boolean"
		},
		"hasQuirksFiles": {
			"description": "Whether this board has a quirks file that needs to be loaded (must be called quirks.cfg and quirks-toolboard.cfg)",
			"type": "boolean"
		},
		"driverCount": {
			"description": "How many drivers this board has",
			"type": "number"
		},
		"integratedDrivers": {
			"description": "Describes the drivers integrated on this board, if any",
			"type": "object",
			"properties": {
				"x": {
					"description": "The driver for the X axis",
					"type": "string"
				},
				"y": {
					"description": "The driver for the Y axis",
					"type": "string"
				},
				"z": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z1": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"z2": {
					"description": "The driver for the Z axis",
					"type": "string"
				},
				"extruder": {
					"description": "The driver for the E axis",
					"type": "string"
				}
			}
		},
		"driverVoltages": {
			"description": "The supported stepper voltages. 24, 36, 48, 56 and 60 is supported. Default is 24 only.",
			"type": "array",
			"items": {
				"type": "number"
			}
		},
		"extruderlessConfig": {
			"description": "The name of an extruderless config (used for 5 driver boards to support 6 driver printers)",
			"type": "string"
		},
		"fourPinFanConnectorCount": {
			"description": "How many 4 pin fan connectors this board has",
			"type": "number"
		},
		"dfu": {
			"description": "DFU Flashing details",
			"type": "object",
			"properties": {
				"dfuBootImage": {
					"description": "Path to a picture for locating the buttons and/or jumpers required to boot into DFU mode",
					"type": "string"
				},
				"flashDevice": {
					"description": "A string containing the vendor and device id to use as the flash target, eg 0483:df11",
					"type": "string"
				},
				"instructions": {
					"description": "Instruction steps for how to boot into DFU mode",
					"type": "array",
					"items": {
						"type": "string"
					}
				},
				"reminder": {
					"description": "Post-flashing reminders, if any.",
					"type": "string"
				},
				"hasBoot0Jumper": {
					"description": "Whether this board has a boot0 jumper",
					"type": "boolean"
				}
			},
			"required": ["dfuBootImage", "flashDevice", "instructions", "hasBoot0Jumper"]
		},
		"sdFileName": {
			"description": "The filename for the firmware binary when flashing via SD card",
			"type": "string"
		}
	},
	"required": ["serialPath", "name", "manufacturer", "firmwareBinaryName", "compileScript", "documentationLink", "driverCount"]
}

=== 3dprintpt/RatOS-configuration/boards/prusa-buddy/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Buddy",
	"manufacturer": "Prusa",
	"serialPath": "/dev/prusa-buddy",
	"firmwareBinaryName": "firmware-prusa-buddy.bin",
	"driverCount": 4,
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://os.ratrig.com/docs/boards/prusa/buddy"
}

=== 3dprintpt/RatOS-configuration/boards/rpi/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Pi",
	"manufacturer": "Raspberry",
	"isHost": true,
	"serialPath": "/tmp/klipper_host_mcu",
	"firmwareBinaryName": "~/klipper/out/klipper.elf",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 0,
	"documentationLink": "https://os.ratrig.com/docs/boards/pi"
}

=== 3dprintpt/RatOS-configuration/boards/fysetc-cheetah-v2/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Cheetah v2",
	"manufacturer": "Fysetc",
	"serialPath": "/dev/fysetc-cheetah-v2",
	"firmwareBinaryName": "firmware-fysetc-cheetah-v2.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 4,
	"documentationLink": "https://os.ratrig.com/docs/boards/fysetc/cheetah-v2"
}

=== 3dprintpt/RatOS-configuration/boards/btt-skr-2-407/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "SKR 2 407",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-skr-2-407",
	"firmwareBinaryName": "firmware-btt-skr-2-407.bin",
	"driverCount": 5,
	"compileScript": "compile.sh",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/skr-2-429"
}

=== 3dprintpt/RatOS-configuration/boards/btt-skr-3-h723/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "SKR 3 H723",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-skr-3-h723",
	"firmwareBinaryName": "firmware-btt-skr-3-h723.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 5,
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/skr-3"
}

=== 3dprintpt/RatOS-configuration/boards/btt-skr-3/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "SKR 3",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-skr-3",
	"firmwareBinaryName": "firmware-btt-skr-3.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"driverCount": 5,
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/skr-3"
}
